### PR TITLE
Remove grv prefix on variables

### PR DESCRIPTION
**Pull request by ebocher**
Not necessary.

### CODE REVIEW

**Comment by nicolas-f** [comment]
This is not necessary to make a distinction between injected variables and local ones ?

**Comment by ebocher** [comment]
Nope but may I have forgot something.

**Comment by nicolas-f** [comment]
It will break all existing groovy codes, is it ok ?

**Comment by ebocher** [comment]
We are polishing OrbisGIS core and its plugins in order to prepare a first release by the end of the year.
Because we are still in snapshot we can remove this prefix.
@SPalominos any point of view ?

**Comment by SPalominos** [comment]
For now, we don't have any groovy script using the 'grv_' variables, so it won't break anything on our side.
I think it's a good thing to rework those kind of things now, because later, once the release will be done, it will be more difficult (or impossible).

**Comment by nicolas-f** [comment]
Ok, please update the version. At least going to 5.1.1-SNAPSHOT

**Comment by SPalominos** [comment]
As we are in a SNAPSHOT version, do we need to upgrade the version for each deep changes ? Won't we be better to do all the changes right now for the 5.1.0 release and then keep it stable for all the futur 5.0.X? It would be easier for us to do those change now and then keep going.

**Comment by nicolas-f** [comment]
I'm talking about the plugin project. This branch is not in snapshot version.

```xml
    <name>Groovy console</name>
<version>5.1.0</version>
```

**Comment by ebocher** [comment]
We will keep the 5.1.0 version and for the next iteration all plugins will follow the same version number defined in the parent pom.
Sure it's not a good practice but this situation has gone on for far too long (https://github.com/orbisgis/orbisgis-plugin_views/commit/bd4425fb5a63ce309ccbb3872774d89bd9c94f58). We are working on a list of tasks https://github.com/orbisgis/orbisgis/issues/1111 to clarify all the OrbisGIS development chain, included plugins. Sorry for the inconvenience.

**Comment by nicolas-f** [comment]
Above good practice, this is a technical limitation, maven and OSGi will not update Jar file if the version is the same (and not in snapshot).

**Comment by ebocher** [comment]
Yep, but users are able to clean the cache of bundles. So because we are in a giant cleaning #1111, we decide to update manually nexus and invite people to clean the bundles.
Anyway when the release goes out,  the users will have to reinstall OrbisGIS and its dependencies. This release is planned to the end of the year so it just a matter of weeks.

**Pull request merged**
